---
# file: site.yml
- hosts: compute
  remote_user: 'pi'
  become: yes

  tasks:
  #role:base
  - name: Install essential utils
    apt:
      name:
        - htop
        - nano
        - git
        - tmux

  #role:tinysetup
  - name: Install utils from TinySetup
    apt:
      name:
        - vim
        - mpich
        - xboxdrv
        - libglew-dev
        - sshpass

