---
# file: site.yml
# Set up all the Raspberry Pi Compute Nodes
- hosts: compute
  remote_user: 'pi'
  become: yes

  tasks:
  #role:base
  - name: Install essential utils
    apt:
      name:
        - htop
        - nano
        - git
        - tmux

  #role:pisettings
  - name: Pi - install our config.txt
    template:
      src: config.txt.j2
      dest: /boot/config.txt
      owner: root
      group: root
      mode: 0755

  #role:tinysetup
  - name: Install utils from TinySetup
    apt:
      name:
        - vim
        - mpich
        - xboxdrv
        - libglew-dev
        - sshpass

  #role:sshkeys
  - name: SSH - Add public key to authorized keys
    authorized_key:
      user: pi
      state: present
      key: "{{ lookup('file', 'ssh/pi.pub') }}"

  - name: SSH - Add private key to all hosts
    copy:
      src: 'ssh/pi.key'
      dest: '/home/pi/.ssh/id_rsa'
      owner: pi
      group: pi
      mode: 0600

  #role:hosts
  - name: Setup hosts file to allow short names
    template:
      src: hosts/hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644

# Set up the prime/"head" node
# This will be used for controlling the simulations
# as well as displaying the results of the simulations.
- hosts: prime
  remote_user: 'pi'
  become: yes

  tasks:
  #role:mpihosts
  - name: Create mpihosts file
    template:
      src: mpi/mpihostsfile.j2
      dest: /home/pi/mpihostsfile
      owner: pi
      group: pi

  - name: Create pi_mpihostsfile as a symlink
    file:
      src: /home/pi/mpihostsfile
      dest: /home/pi/pi_mpihostsfile
      state: link

  #role:startsph
  - name: Init - install custom startsph script used to start simulations
    template:
      src: startsph.j2
      dest: /home/pi/startsph
      owner: pi
      group: pi
      mode: 0755

  #role:demo-SPH
  - name: SPH - Install custom makefile
    template:
      src: demo-SPH/makefile.j2
      dest: /home/pi/SPH/makefile
      owner: pi
      group: pi
      mode: 0644

  #role:demo-PiBrot
  - name: PiBrot - Install custom makefile
    template:
      src: demo-PiBrot/Makefile.j2
      dest: /home/pi/PiBrot/Makefile
      owner: pi
      group: pi
      mode: 0644
